### ISSUE TITLE
Regularization on xCNN

### ISSUE THREAD

**Issue by zwep** [kumarak93/LinearConv#1]
Hi,

I have tried to run your code and train a model of mine with it. But I stumble upon the increase in loss when I added the regularization correction on the xCNN weights.
Applying that to the low-rank version of your layer I get an huge increase. Have you ever found something like that as well? Or is this correction only meant for the vanilla implementation?

Greetings,
Seb

**Comment by kkahatapitiya** [comment]
This regularization loss depends on the size of weights in your model. You should probably set your regularization strength to match your original loss. Please refer:
(https://github.com/kumarak93/LinearConv/blob/788a43a2aeda14d860ec7e470c556b1bc9e02670/models/vgg_xcnn.py#L369)
