### ISSUE TITLE
Can we use LinearConv in image reconstruction tasks such as image denoising？

### ISSUE THREAD

**Issue by hellolingling** [kumarak93/LinearConv#2]
Hi @kkahatapitiya ，can we use LinearConv in image reconstruction tasks?
When I use LinearConv in image denoising, the color of the result image is not right. The loss of the tasks contains L1 loss of the (label-out) and regularization loss of weight. Can you please find what's the problem of my job?

**Comment by kkahatapitiya** [comment]
I haven't used LinearConv blocks in image generation tasks, but I can't see a reason why it shouldn't work. I would suggest you to look into the magnitudes of the loss terms; usually you need to set your regularization strength to match the scale of your original loss (L1 in your case). Check whether your regularization loss is way larger than L1 loss.

**Comment by hellolingling** [comment]
Thank you! I have found the solution. As the channel of activation layer is 3(too small), I use normal conv in this layer, then the color of the out is right.
